version: "1.0"
services:
 backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-docker-dev
    ports:
      - 4000:3001
    env_file: ./.env
    networks:
      - backend
    depends_on:
      - db
 db:
   container_name: postgres
   image: postgres
   env_file: ./.env
   restart: always
   networks:
     - backend
   volumes:
     - db_data:/data/postrgres


 frontend:
  container_name: frontend
  build:
    context: frontend
    dockerfile: Dockerfile
  image: frontend-docker-dev
  ports:
    - 8080:80
  networks:
    - frontend


networks:
  backend:
  frontend:

volumes:
  db_data:
